import re
import sys
import typer
from typing import Optional
import subprocess
import shutil
from pathlib import Path
from datetime import datetime, UTC

# Use UTF-8 for stdout/stderr so emojis work on Windows (e.g. when cp1252 is default)
def _ensure_utf8():
    if sys.platform == "win32":
        try:
            import ctypes
            kernel32 = ctypes.windll.kernel32  # type: ignore[attr-defined]
            kernel32.SetConsoleOutputCP(65001)  # UTF-8
            kernel32.SetConsoleCP(65001)
        except Exception:
            pass
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure") and getattr(stream, "encoding", "").lower() != "utf-8":
            try:
                stream.reconfigure(encoding="utf-8")
            except Exception:
                pass


_ensure_utf8()

# No `import rich` here: PyInstaller would need every lazy unicode submodule, and Typer only
# pulls Rich in for help/error formatting. Use plain Typer/Click output instead.
app = typer.Typer(rich_markup_mode=None, add_completion=False)
BUILD_INFO_MODULE_NAME = "_pybin_build_info"


def _source_references_build_info(file_path: Path) -> bool:
    try:
        return BUILD_INFO_MODULE_NAME in file_path.read_text(encoding="utf-8")
    except Exception:
        return False


def _render_build_info_module(build_time_utc: datetime) -> str:
    build_time_iso = build_time_utc.astimezone(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    return (
        "# Auto-generated by pybin during packaging.\n"
        f'BUILD_TIMESTAMP_UTC = "{build_time_iso}"\n'
        'BUILD_TOOL = "pybin"\n'
    )


def _prepare_build_info_module(base_dir: Path):
    build_info_path = base_dir / f"{BUILD_INFO_MODULE_NAME}.py"
    original_contents = None

    if build_info_path.exists():
        original_contents = build_info_path.read_text(encoding="utf-8")

    build_info_path.write_text(_render_build_info_module(datetime.now(UTC)), encoding="utf-8")
    return build_info_path, original_contents


def _restore_build_info_module(build_info_path: Path, original_contents) -> None:
    if original_contents is None:
        if build_info_path.exists():
            build_info_path.unlink()
        return

    build_info_path.write_text(original_contents, encoding="utf-8")


def _normalize_exe_basename(name: str) -> str:
    """Strip .exe for PyInstaller --name (it adds the suffix on Windows)."""
    n = name.strip()
    if n.lower().endswith(".exe"):
        return n[:-4]
    return n


def _script_imports_rich(script_path: Path) -> bool:
    """True if the script appears to depend on Rich (needs extra PyInstaller hidden imports)."""
    try:
        text = script_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("from rich") or stripped.startswith("import rich"):
            return True
    return False


def _extract_spec_entry_script(spec_text: str) -> Optional[str]:
    match = re.search(
        r"a = Analysis\(\s*\[(?:\s*)['\"]([^'\"]+)['\"]",
        spec_text,
        flags=re.DOTALL,
    )
    if not match:
        return None
    return match.group(1)


def _is_windows_abs_path(path_string: str) -> bool:
    return bool(re.match(r"^[A-Za-z]:[\\/]", path_string))


def _spec_looks_compatible(spec_path: Path, script_path: Path) -> tuple[bool, str]:
    """
    Check whether the spec's Analysis entry is portable for the current platform.
    Returns (compatible, reason_if_not).
    """
    try:
        text = spec_path.read_text(encoding="utf-8")
    except Exception as exc:
        return False, f"could not read spec: {exc}"

    entry = _extract_spec_entry_script(text)
    if not entry:
        return False, "could not parse Analysis entry"

    if _is_windows_abs_path(entry) and sys.platform != "win32":
        return False, "contains Windows absolute path on non-Windows"
    if entry.startswith("/") and sys.platform == "win32":
        return False, "contains POSIX absolute path on Windows"

    if _is_windows_abs_path(entry) or Path(entry).is_absolute():
        return False, "contains machine-specific absolute path"

    if Path(entry).name != script_path.name:
        return False, f"entry points to '{entry}' instead of '{script_path.name}'"

    return True, ""


def _patch_regenerated_spec(
    spec_path: Path,
    *,
    entry_basename: str,
    ensure_rich: bool,
) -> None:
    """After pyi-makespec: portable entry script and Rich unicode tables (spec-only; no CLI hooks)."""
    text = spec_path.read_text(encoding="utf-8")
    text = re.sub(
        r"(a = Analysis\(\s*)\[['\"][^'\"]+['\"]\]",
        rf"\1['{entry_basename}']",
        text,
        count=1,
    )
    if ensure_rich:
        if 'collect_submodules("rich._unicode_data")' not in text:
            header = (
                "from PyInstaller.utils.hooks import collect_submodules\n\n"
                '_RICH_UNICODE_SUBMODULES = collect_submodules("rich._unicode_data")\n\n'
            )
            lines = text.splitlines(keepends=True)
            insert_at = 1
            if len(lines) > 1 and lines[1].strip() == "":
                insert_at = 2
            else:
                lines.insert(1, "\n")
                insert_at = 2
            lines.insert(insert_at, header)
            text = "".join(lines)
        text = re.sub(
            r"\n(\s*)hiddenimports=\[[^\]]*\],",
            r"\n\1hiddenimports=_RICH_UNICODE_SUBMODULES,",
            text,
            count=1,
        )
    spec_path.write_text(text, encoding="utf-8")


def _resolve_built_artifact_path(
    dist_path: Path,
    file_path: Path,
    *,
    output_name: Optional[str] = None,
) -> Path:
    stem = _normalize_exe_basename(output_name) if output_name else file_path.stem
    candidates = []
    if sys.platform == "win32":
        candidates.append(dist_path / f"{stem}.exe")
    candidates.append(dist_path / stem)

    for candidate in candidates:
        if candidate.exists():
            return candidate
    return candidates[0]


# ============================================================================ #
#                                FUNCTION: main                                #
# ============================================================================ #
@app.command()
def main(
    file: Path = typer.Argument(..., help="Python file to process"),
    keep_spec: bool = typer.Option(
        True,
        "--keep-spec/--no-keep-spec",
        help="Keep the .spec file after building (default: keep)",
        show_default=True,
    ),
    keep_build: bool = typer.Option(
        False,
        "--keep-build",
        help="Keep the build directory after building",
    ),
    use_spec: bool = typer.Option(
        False,
        "--use-spec/--no-use-spec",
        help=(
            "Use .spec workflow when available. Incompatible specs are auto-regenerated. "
            "Use --no-use-spec to always build directly from .py."
        ),
        show_default=True,
    ),
    output_dir: Path = typer.Option(
        None,
        "--output-dir",
        help="Directory for the final .exe (default: <script_dir>/dist).",
    ),
    name: Optional[str] = typer.Option(
        None,
        "--name",
        "-n",
        help=(
            "Base name of the output executable without .exe (PyInstaller --name). "
            "Default: same stem as the .py file. "
            "Writes <name>.exe into --output-dir or the default dist/ folder."
        ),
    ),
):
    """
    Compile one Python script to a single-file executable (PyInstaller), then optionally remove build noise.

    \b
    Default artifact: <script_dir>/dist/<script_stem>.exe
    \b
    Change only the folder:  --output-dir PATH
    Change only the .exe name:  --name STEM  (or -n STEM); still uses default dist/ unless you also pass --output-dir.
    """
    if not file.exists():
        typer.secho(f"✗ Error: File '{file}' does not exist.", fg=typer.colors.RED, bold=True, err=True)
        raise typer.Exit(code=1)

    if file.suffix != ".py":
        typer.secho(f"✗ Error: '{file}' is not a Python file.", fg=typer.colors.RED, bold=True, err=True)
        raise typer.Exit(code=1)

    typer.secho(f"📦 Processing: {file}", fg=typer.colors.CYAN, bold=True)

    script_for_analysis = file.resolve()
    script_imports_rich = _script_imports_rich(script_for_analysis)

    # Determine base paths (use script directory to keep outputs next to the script)
    base_dir = script_for_analysis.parent
    dist_path = output_dir.resolve() if output_dir else base_dir / "dist"
    work_path = base_dir / "build"
    spec_path = base_dir
    spec_file = spec_path / f"{file.stem}.spec"

    # Ensure output directory exists
    dist_path.mkdir(parents=True, exist_ok=True)

    build_info_path = None
    original_build_info = None
    should_embed_build_info = _source_references_build_info(file.resolve())
    if should_embed_build_info:
        try:
            build_info_path, original_build_info = _prepare_build_info_module(base_dir)
            typer.secho(f"  Embedded build metadata via {build_info_path.name}", dim=True)
        except Exception as exc:
            typer.secho(f"⚠ Could not embed build metadata: {exc}", fg=typer.colors.YELLOW)
    else:
        typer.secho(
            f"  Skipping build metadata: {file.name} does not reference {BUILD_INFO_MODULE_NAME}",
            dim=True,
        )

    try:
        should_build_with_spec = use_spec
        should_regenerate_spec = False

        if use_spec:
            if spec_file.exists():
                typer.secho(f"✓ Found existing .spec file: {spec_file.name}", fg=typer.colors.GREEN)
                compatible, reason = _spec_looks_compatible(spec_file, script_for_analysis)
                if not compatible:
                    should_regenerate_spec = True
                    typer.secho(
                        f"⚠ Existing .spec is incompatible ({reason}); regenerating",
                        fg=typer.colors.YELLOW,
                    )
                else:
                    try:
                        src_mtime = file.stat().st_mtime
                        spec_mtime = spec_file.stat().st_mtime
                    except Exception:
                        src_mtime = None
                        spec_mtime = None
                    if src_mtime is not None and spec_mtime is not None and src_mtime > spec_mtime:
                        should_regenerate_spec = True
                        typer.secho(
                            "⚠ Source is newer than .spec; regenerating .spec (backup saved)",
                            fg=typer.colors.YELLOW,
                        )
            else:
                should_regenerate_spec = True
                typer.secho("⚙ No existing .spec; generating one", fg=typer.colors.YELLOW)

            if should_regenerate_spec:
                if spec_file.exists():
                    backup_spec = spec_file.with_suffix(spec_file.suffix + ".bak")
                    try:
                        shutil.copy2(spec_file, backup_spec)
                    except Exception:
                        typer.secho(
                            "✗ Failed to backup existing .spec; continuing without backup",
                            fg=typer.colors.RED,
                            err=True,
                        )

                makespec_cmd = [
                    "pyi-makespec",
                    "--onefile",
                    f"--specpath={spec_path}",
                    file.name,
                ]
                mk = subprocess.run(makespec_cmd, capture_output=True, text=True, cwd=str(base_dir))
                if mk.returncode != 0:
                    typer.secho("✗ pyi-makespec failed", fg=typer.colors.RED, err=True)
                    typer.secho(mk.stderr, fg=typer.colors.RED, err=True)
                    raise typer.Exit(code=1)

                typer.secho("✓ .spec regenerated", fg=typer.colors.GREEN)
                try:
                    _patch_regenerated_spec(
                        spec_file,
                        entry_basename=file.name,
                        ensure_rich=script_imports_rich,
                    )
                except Exception as exc:
                    typer.secho(f"⚠ Could not patch regenerated .spec: {exc}", fg=typer.colors.YELLOW)

            cmd = [
                "pyinstaller",
                f"--distpath={dist_path}",
                f"--workpath={work_path}",
            ]
            if name:
                cmd.append(f"--name={_normalize_exe_basename(name)}")
            cmd.append(str(spec_file))
        else:
            typer.secho("⚙ Building directly from script (--no-use-spec)", fg=typer.colors.YELLOW)
            cmd = [
                "pyinstaller",
                "--onefile",
                f"--distpath={dist_path}",
                f"--workpath={work_path}",
                f"--specpath={spec_path}",
            ]
            if script_imports_rich:
                cmd.append("--collect-submodules=rich._unicode_data")
            if name:
                cmd.append(f"--name={_normalize_exe_basename(name)}")
            cmd.append(file.name)
        # Run from the script directory; basename keeps generated .spec files portable (no machine paths)
        result = subprocess.run(cmd, capture_output=True, text=True, cwd=str(base_dir))
        if result.returncode != 0:
            typer.secho("✗ PyInstaller failed:", fg=typer.colors.RED, bold=True, err=True)
            typer.secho(result.stderr, fg=typer.colors.RED, err=True)
            raise typer.Exit(code=1)

        typer.secho("✓ PyInstaller completed successfully", fg=typer.colors.GREEN, bold=True)
        
        # Clean up build directory (cross-platform) if not keeping it
        if not keep_build:
            if work_path.exists():
                shutil.rmtree(work_path)
                typer.secho("  Cleaned up build directory", dim=True)
        else:
            typer.secho("  Keeping build directory (--keep-build)", fg=typer.colors.YELLOW)
        
        # Clean up spec file if not keeping it
        if not keep_spec:
            if spec_file.exists():
                spec_file.unlink()
                typer.secho("  Cleaned up .spec file", dim=True)
        elif keep_spec and not spec_file.exists():
            # Only show message if user explicitly set --keep-spec but no spec was generated
            pass
        
        built_artifact = _resolve_built_artifact_path(dist_path, file, output_name=name)
        typer.echo("")
        typer.secho("✓ Build complete: ", fg=typer.colors.GREEN, bold=True, nl=False)
        typer.secho(str(built_artifact), fg=typer.colors.CYAN, bold=True)
    finally:
        if build_info_path is not None:
            _restore_build_info_module(build_info_path, original_build_info)



if __name__ == "__main__":
    app()