import sys
import typer
from typing import Optional
import subprocess
import shutil
from pathlib import Path
from datetime import datetime, UTC

# Use UTF-8 for stdout/stderr so emojis work on Windows (e.g. when cp1252 is default)
def _ensure_utf8():
    if sys.platform == "win32":
        try:
            import ctypes
            kernel32 = ctypes.windll.kernel32  # type: ignore[attr-defined]
            kernel32.SetConsoleOutputCP(65001)  # UTF-8
            kernel32.SetConsoleCP(65001)
        except Exception:
            pass
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure") and getattr(stream, "encoding", "").lower() != "utf-8":
            try:
                stream.reconfigure(encoding="utf-8")
            except Exception:
                pass


_ensure_utf8()

from rich.console import Console

app = typer.Typer()
console = Console()
BUILD_INFO_MODULE_NAME = "_pybin_build_info"

# ============================================================================ #
#                               FUNCTION: cprint                               #
# ============================================================================ #
def cprint(message: str, type: str = "", style: str = "bold green", **kwargs) -> None:
    prefix = f"[{datetime.now().strftime('%H:%M:%S')}]"
    type   = type.lower()
    
    if type == "error":
        style = "red"
        prefix = "❌"
    elif type == "warning":
        style = "yellow"
        prefix = "⚠️"
    elif type == "info":
        style = "blue"
        prefix = "ℹ️"
    elif type == "success":
        style = "green"
        prefix = "✅"
    message = f"{prefix}  {message}"
    console.print(message, style=style, **kwargs)


def _source_references_build_info(file_path: Path) -> bool:
    try:
        return BUILD_INFO_MODULE_NAME in file_path.read_text(encoding="utf-8")
    except Exception:
        return False


def _render_build_info_module(build_time_utc: datetime) -> str:
    build_time_iso = build_time_utc.astimezone(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    return (
        "# Auto-generated by pybin during packaging.\n"
        f'BUILD_TIMESTAMP_UTC = "{build_time_iso}"\n'
        'BUILD_TOOL = "pybin"\n'
    )


def _prepare_build_info_module(base_dir: Path):
    build_info_path = base_dir / f"{BUILD_INFO_MODULE_NAME}.py"
    original_contents = None

    if build_info_path.exists():
        original_contents = build_info_path.read_text(encoding="utf-8")

    build_info_path.write_text(_render_build_info_module(datetime.now(UTC)), encoding="utf-8")
    return build_info_path, original_contents


def _restore_build_info_module(build_info_path: Path, original_contents) -> None:
    if original_contents is None:
        if build_info_path.exists():
            build_info_path.unlink()
        return

    build_info_path.write_text(original_contents, encoding="utf-8")


def _normalize_exe_basename(name: str) -> str:
    """Strip .exe for PyInstaller --name (it adds the suffix on Windows)."""
    n = name.strip()
    if n.lower().endswith(".exe"):
        return n[:-4]
    return n


def _resolve_built_artifact_path(
    dist_path: Path,
    file_path: Path,
    *,
    output_name: Optional[str] = None,
) -> Path:
    stem = _normalize_exe_basename(output_name) if output_name else file_path.stem
    candidates = []
    if sys.platform == "win32":
        candidates.append(dist_path / f"{stem}.exe")
    candidates.append(dist_path / stem)

    for candidate in candidates:
        if candidate.exists():
            return candidate
    return candidates[0]


# ============================================================================ #
#                                FUNCTION: main                                #
# ============================================================================ #
@app.command()
def main(
    file: Path = typer.Argument(..., help="Python file to process"),
    keep_spec: bool = typer.Option(
        True,
        "--keep-spec/--no-keep-spec",
        help="Keep the .spec file after building (default: keep)",
        show_default=True,
        rich_help_panel="Build",
    ),
    keep_build: bool = typer.Option(
        False,
        "--keep-build",
        help="Keep the build directory after building",
        rich_help_panel="Build",
    ),
    output_dir: Path = typer.Option(
        None,
        "--output-dir",
        help="Directory for the final .exe (default: <script_dir>/dist).",
        rich_help_panel="Output",
    ),
    name: Optional[str] = typer.Option(
        None,
        "--name",
        "-n",
        help=(
            "Base name of the output executable without .exe (PyInstaller --name). "
            "Default: same stem as the .py file. "
            "Writes <name>.exe into --output-dir or the default dist/ folder."
        ),
        rich_help_panel="Output",
    ),
):
    """
    Compile one Python script to a single-file executable (PyInstaller), then optionally remove build noise.

    \b
    Default artifact: <script_dir>/dist/<script_stem>.exe
    \b
    Change only the folder:  --output-dir PATH
    Change only the .exe name:  --name STEM  (or -n STEM); still uses default dist/ unless you also pass --output-dir.
    """
    if not file.exists():
        console.print(f"[red]✗ Error:[/red] File '{file}' does not exist.", style="bold")
        raise typer.Exit(code=1)
    
    if file.suffix != ".py":
        console.print(f"[red]✗ Error:[/red] '{file}' is not a Python file.", style="bold")
        raise typer.Exit(code=1)
    
    console.print(f"[cyan]📦 Processing:[/cyan] {file}", style="bold")

    # Determine base paths (use script directory to keep outputs next to the script)
    base_dir = file.resolve().parent
    dist_path = output_dir.resolve() if output_dir else base_dir / "dist"
    work_path = base_dir / "build"
    spec_path = base_dir
    spec_file = spec_path / f"{file.stem}.spec"

    # Ensure output directory exists
    dist_path.mkdir(parents=True, exist_ok=True)

    build_info_path = None
    original_build_info = None
    should_embed_build_info = _source_references_build_info(file.resolve())
    if should_embed_build_info:
        try:
            build_info_path, original_build_info = _prepare_build_info_module(base_dir)
            console.print(f"[dim]  Embedded build metadata via {build_info_path.name}[/dim]")
        except Exception as exc:
            console.print(f"[yellow]⚠ Could not embed build metadata:[/yellow] {exc}")
    else:
        console.print(f"[dim]  Skipping build metadata: {file.name} does not reference {BUILD_INFO_MODULE_NAME}[/dim]")

    try:
        # Run pyinstaller with explicit paths
        # If a .spec file exists, use it directly to preserve custom settings
        if spec_file.exists():
            console.print(f"[green]✓ Found existing .spec file:[/green] {spec_file.name}")

            # If the source file is newer than the spec, regenerate the spec
            try:
                src_mtime = file.stat().st_mtime
                spec_mtime = spec_file.stat().st_mtime
            except Exception:
                src_mtime = None
                spec_mtime = None

            if src_mtime is not None and spec_mtime is not None and src_mtime > spec_mtime:
                console.print("[yellow]⚠ Source is newer than .spec; regenerating .spec (backup saved)[/yellow]")
                # Backup existing spec
                backup_spec = spec_file.with_suffix(spec_file.suffix + ".bak")
                try:
                    shutil.copy2(spec_file, backup_spec)
                except Exception:
                    console.print("[red]✗ Failed to backup existing .spec; continuing without backup[/red]")

                makespec_cmd = [
                    "pyi-makespec",
                    "--onefile",
                    f"--specpath={spec_path}",
                    file.name,
                ]
                mk = subprocess.run(makespec_cmd, capture_output=True, text=True, cwd=str(base_dir))
                if mk.returncode != 0:
                    console.print("[red]✗ pyi-makespec failed; using existing .spec[/red]")
                    console.print(mk.stderr, style="red")
                else:
                    console.print("[green]✓ .spec regenerated[/green]")

            cmd = [
                "pyinstaller",
                f"--distpath={dist_path}",
                f"--workpath={work_path}",
            ]
            if name:
                cmd.append(f"--name={_normalize_exe_basename(name)}")
            cmd.append(str(spec_file))
        else:
            console.print("[yellow]⚙ Generating new .spec file[/yellow]")
            cmd = [
                "pyinstaller",
                "--onefile",
                f"--distpath={dist_path}",
                f"--workpath={work_path}",
                f"--specpath={spec_path}",
            ]
            if name:
                cmd.append(f"--name={_normalize_exe_basename(name)}")
            cmd.append(file.name)
        # Run from the script directory; basename keeps generated .spec files portable (no machine paths)
        result = subprocess.run(cmd, capture_output=True, text=True, cwd=str(base_dir))
        if result.returncode != 0:
            console.print("[red]✗ PyInstaller failed:[/red]", style="bold")
            console.print(result.stderr, style="red")
            raise typer.Exit(code=1)
        
        console.print("[green]✓ PyInstaller completed successfully[/green]", style="bold")
        
        # Clean up build directory (cross-platform) if not keeping it
        if not keep_build:
            if work_path.exists():
                shutil.rmtree(work_path)
                console.print("[dim]  Cleaned up build directory[/dim]")
        else:
            console.print("[yellow]  Keeping build directory (--keep-build)[/yellow]")
        
        # Clean up spec file if not keeping it
        if not keep_spec:
            if spec_file.exists():
                spec_file.unlink()
                console.print("[dim]  Cleaned up .spec file[/dim]")
        elif keep_spec and not spec_file.exists():
            # Only show message if user explicitly set --keep-spec but no spec was generated
            pass
        
        built_artifact = _resolve_built_artifact_path(dist_path, file, output_name=name)
        console.print(f"\n[green]✓ Build complete:[/green] [cyan]{built_artifact}[/cyan]", style="bold")
    finally:
        if build_info_path is not None:
            _restore_build_info_module(build_info_path, original_build_info)



if __name__ == "__main__":
    app()